name: hk

permissions:
  contents: read
  packages: read
  statuses: write

on:
  push:
    branches: [master]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: hugoh/gh-workflows/setup@6b3318af9824bf310afc501232f53a99083296cd # v1.7.1
      - run: uv sync
      - run: uv run pytest
      - uses: hugoh/gh-workflows/hk-check@6b3318af9824bf310afc501232f53a99083296cd # v1.7.1
        env:
          PINACT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
