name: release

on:
  push:
    branches:
      - master

permissions: {}

jobs:
  release:
    uses: hugoh/gh-workflows/.github/workflows/release.yml@1d2a18056f2122b7f49c2e8aacb48c40cb6eaab9 # v1.24.0
    permissions:
      contents: write

  publish-pypi:
    needs: release
    if: needs.release.outputs.tag != ''
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ needs.release.outputs.tag }}

      - uses: hugoh/gh-workflows/setup@1d2a18056f2122b7f49c2e8aacb48c40cb6eaab9 # v1.24.0

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
